---
title: "607_Assignment1_MushroomDS"
author: "SantoshCheruku"
date: "January 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Retrieve dataset from uci site and create a dataframe
```{r}
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
#rawData <- readLines(url)
#mushroomDF <- read.csv(textConnection(rawData), header = F, stringsAsFactors = F)

mushroomDF <- read.csv(url, header = F, stringsAsFactors = F)

summary(mushroomDF)
```

### Assign column names to the dataset
```{r}
colnames(mushroomDF) <- c("class", "cap_shape", "cap_surface", "cap_color", 
                       "bruises", "odor", "gill_attachment", 
                       "gill_spacing",	"gill_size", "gill_color",
                       "stalk_shape", "stalk_root", "stalk_surface_above_ring",
                       "stalk_surface_below_ring",	"stalk_color_above_ring", "stalk_color_above_ring",
                       "veil_type", "veil_color", "ring_number", "ring_type", 
                       "spore_print_color",	"population", "habitat")
colnames(mushroomDF)
```

### Create a subset of dataframes using a limited set of columns
``` {r}
mushroomSubSetDF <- subset(mushroomDF, subset = cap_color==c("b","p"), select = c("class", "cap_color", "cap_surface", "odor","veil_type", "veil_color"))
mushroomSubSetDF
```

### Identify expanded values for the abbreviated data in the selected cols
```{r}
class_values <- c(e='edible', p='poisonous')
cap_surface_values <- c(f='fibrous',g='grooves',y='scaly',s='smooth')
cap_color_values <- c(n='brown',b='buff',c='cinnamon',g='gray',r='green', p='pink',u='purple',e='red',w='white',y='yellow')
odor_values <- c(a='almond',l='anise',c='creosote',y='fishy',f='foul', m='musty',n='none',p='pungent',s='spicy')
veil_type_values <- c(  p='partial',u='universal')
veil_color_values <- c( n='brown',o='orange',w='white',y='yellow')
```

### Replace the abbreviated values with the expanded data
```{r}
mushroomSubSetDF$class[mushroomSubSetDF$class=="e"] <- class_values["e"]
mushroomSubSetDF$class[mushroomSubSetDF$class=="p"] <- class_values["p"] 


mushroomSubSetDF$cap_surface[mushroomSubSetDF$cap_surface=="f"] <- cap_surface_values["f"] 
mushroomSubSetDF$cap_surface[mushroomSubSetDF$cap_surface=="g"] <- cap_surface_values["g"] 
mushroomSubSetDF$cap_surface[mushroomSubSetDF$cap_surface=="y"] <- cap_surface_values["y"] 
mushroomSubSetDF$cap_surface[mushroomSubSetDF$cap_surface=="s"] <- cap_surface_values["s"] 


mushroomSubSetDF$cap_color[mushroomSubSetDF$cap_color=="b"] <- cap_color_values["b"] 
mushroomSubSetDF$cap_color[mushroomSubSetDF$cap_color=="p"] <- cap_color_values["p"] 

mushroomSubSetDF$odor[mushroomSubSetDF$odor=="a"] <- odor_values["a"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="l"] <- odor_values["l"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="c"] <- odor_values["c"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="y"] <- odor_values["y"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="f"] <- odor_values["f"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="m"] <- odor_values["m"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="n"] <- odor_values["n"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="p"] <- odor_values["p"] 
mushroomSubSetDF$odor[mushroomSubSetDF$odor=="s"] <- odor_values["s"] 

mushroomSubSetDF$veil_type[mushroomSubSetDF$veil_type=="p"] <- veil_type_values["p"] 
mushroomSubSetDF$veil_type[mushroomSubSetDF$veil_type=="u"] <- veil_type_values["u"]

mushroomSubSetDF$veil_color[mushroomSubSetDF$veil_color=="n"] <- veil_color_values["n"] 
mushroomSubSetDF$veil_color[mushroomSubSetDF$veil_color=="o"] <- veil_color_values["o"] 
mushroomSubSetDF$veil_color[mushroomSubSetDF$veil_color=="w"] <- veil_color_values["w"] 
mushroomSubSetDF$veil_color[mushroomSubSetDF$veil_color=="y"] <- veil_color_values["y"] 

```

### Created two new columns which can represent some meaningful data
```{r}

mushroomSubSetDF$isPungent <- mushroomSubSetDF$odor=='pungent'
mushroomSubSetDF$isSmoothSurface <- mushroomSubSetDF$cap_surface=='smooth'
mushroomSubSetDF
```





